config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the unauthenticated root path route ("/")
  unauthenticated do
    root 'public#home'
  end

  # Defines the authenticated root path route ("/") for the User model
  authenticated :user do
    root 'dashboard#show', as: :authenticated_root
  end

  # Public routes
  get 'help', to: 'public#help'
  get 'about', to: 'public#about'
  get 'contact', to: 'public#contact'

  # Defines the routes for the Devise User model
  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations',
                            passwords: 'users/passwords',
                            unlocks: 'users/unlocks',
                            confirmations: 'users/confirmations' },
             path: '',
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'signup',
                           edit: 'profile' }

  namespace :common do
    resources :measure_units
    resources :measure_unit_types
    resources :languages
    resources :timezones
    resources :currencies
    resources :countries
  end

  namespace :organization do
    resources :plants do
      member do
        get :areas
      end
    end

    resources :areas do
      member do
        get :production_lines
      end
    end

    resources :production_lines
  end

  namespace :maintenance do
    resources :plans do
      collection do
        get :new_resource_fields
      end
    end
    resources :technicians
    resources :manufacturers
    resources :asset_types

    resources :assets do
      resources :asset_documents, path: 'documents', shallow: true
      resources :asset_assignees, path: 'assignees', shallow: true,
                only: %i[ index create destroy ]

      member do
        get :components, defaults: { format: :turbo_stream }
      end
    end
  end

  namespace :settings do
    root 'general#index'
  end
end

app/models/organization.rb
# frozen_string_literal: true

module Organization
  def self.table_name_prefix
    'organization_'
  end
end

app/models/organization/area.rb
# frozen_string_literal: true

class Organization::Area < ApplicationRecord
  # -- -------------------------------------------------------------------------
  # -- Constants ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Concerns ----------------------------------------------------------------
  include HasEnumState

  # -- -------------------------------------------------------------------------
  # -- Attributes --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Extensions --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Enums -------------------------------------------------------------------
  has_enum_state :status

  # -- -------------------------------------------------------------------------
  # -- Associations ------------------------------------------------------------
  belongs_to :plant, class_name: 'Organization::Plant',
             foreign_key: :organization_plant_id

  has_many :production_lines, class_name: 'Organization::ProductionLine',
           foreign_key: :organization_area_id, dependent: :restrict_with_error

  # -- -------------------------------------------------------------------------
  # -- Validations -------------------------------------------------------------
  validates :code, presence: true, length: { maximum: 10 },
            uniqueness: { scope: :organization_plant_id }
  validates :name, presence: true, length: { maximum: 100 }

  # -- -------------------------------------------------------------------------
  # -- Callbacks ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Scopes ------------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Delegations -------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Class Methods -----------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Instance Methods --------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Private Methods ---------------------------------------------------------
end

app/controllers/organization/areas_controller.rb
# frozen_string_literal: true

class Organization::AreasController < ApplicationController
  # -- -------------------------------------------------------------------------
  # -- Constants ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Concerns ----------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Extensions --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Callbacks ------------------------------------------------
  before_action :set_organization_area, only: %i[ show edit update destroy production_lines ]

  # -- -------------------------------------------------------------------------
  # -- Helper methods ----------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Actions -----------------------------------------------------------------

  # GET /organization/areas or /organization/areas.json
  def index
    @pagy, @records = pagy(Organization::Area.all)
  end

  # GET /organization/areas/1 or /organization/areas/1.json
  def show
  end

  # GET /organization/areas/new
  def new
    @organization_area = Organization::Area.new
  end

  # GET /organization/areas/1/edit
  def edit
  end

  # POST /organization/areas or /organization/areas.json
  def create
    @organization_area = Organization::Area.new(organization_area_params)

    respond_to do |format|
      if @organization_area.save
        format.html { redirect_to @organization_area, notice: t('.notice') }
        format.json { render :show, status: :created, location: @organization_area }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization/areas/1 or /organization/areas/1.json
  def update
    respond_to do |format|
      if @organization_area.update(organization_area_params)
        format.html { redirect_to @organization_area, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @organization_area }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization/areas/1 or /organization/areas/1.json
  def destroy
    @organization_area.destroy!

    respond_to do |format|
      format.html { redirect_to organization_areas_path, status: :see_other, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  def production_lines
    production_lines = Organization::Area.find(params[:id]).production_lines
    render turbo_stream: turbo_stream.replace(
      'production_lines_select',
      partial: 'organization/production_lines/production_line_select',
      locals: { production_lines: production_lines }
    )
  end

  # -- -------------------------------------------------------------------------
  # -- Protected Methods -------------------------------------------------------

  protected

  # -- -------------------------------------------------------------------------
  # -- Private Methods ---------------------------------------------------------

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_organization_area
      @organization_area = Organization::Area.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def organization_area_params
      params.expect(organization_area: %i[code name description organization_plant_id status])
    end
end

app/controllers/organization/plants_controller.rb
# frozen_string_literal: true

class Organization::PlantsController < ApplicationController
  # -- -------------------------------------------------------------------------
  # -- Constants ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Concerns ----------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Extensions --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Callbacks ------------------------------------------------
  before_action :set_organization_plant, only: %i[ show edit update destroy areas ]

  # -- -------------------------------------------------------------------------
  # -- Helper methods ----------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Actions -----------------------------------------------------------------

  # GET /organization/plants or /organization/plants.json
  def index
    @pagy, @records = pagy(Organization::Plant.all)
  end

  # GET /organization/plants/1 or /organization/plants/1.json
  def show
  end

  # GET /organization/plants/new
  def new
    @organization_plant = Organization::Plant.new
  end

  # GET /organization/plants/1/edit
  def edit
  end

  # POST /organization/plants or /organization/plants.json
  def create
    @organization_plant = Organization::Plant.new(organization_plant_params)

    respond_to do |format|
      if @organization_plant.save
        format.html { redirect_to @organization_plant, notice: t('.notice') }
        format.json { render :show, status: :created, location: @organization_plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization_plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization/plants/1 or /organization/plants/1.json
  def update
    respond_to do |format|
      if @organization_plant.update(organization_plant_params)
        format.html { redirect_to @organization_plant, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @organization_plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization_plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization/plants/1 or /organization/plants/1.json
  def destroy
    @organization_plant.destroy!

    respond_to do |format|
      format.html { redirect_to organization_plants_path, status: :see_other, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  def areas
    areas = @organization_plant.areas
    render turbo_stream: turbo_stream.replace(
      'areas_select',
      partial: 'organization/areas/area_select',
      locals: { areas: areas }
    )
  end

  # -- -------------------------------------------------------------------------
  # -- Protected Methods -------------------------------------------------------

  protected

  # -- -------------------------------------------------------------------------
  # -- Private Methods ---------------------------------------------------------

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_organization_plant
      @organization_plant = Organization::Plant.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def organization_plant_params
      params.expect(organization_plant: %i[code name address status])
    end
end

app/controllers/organization/production_lines_controller.rb
# frozen_string_literal: true

class Organization::ProductionLinesController < ApplicationController
  # -- -------------------------------------------------------------------------
  # -- Constants ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Concerns ----------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Extensions --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Callbacks ---------------------------------------------------------------
  before_action :set_organization_production_line, only: %i[ show edit update destroy ]

  # -- -------------------------------------------------------------------------
  # -- Helper methods ----------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Actions -----------------------------------------------------------------

  # GET /organization/production_lines or /organization/production_lines.json
  def index
    @pagy, @records = pagy(Organization::ProductionLine.all)
  end

  # GET /organization/production_lines/1 or /organization/production_lines/1.json
  def show
  end

  # GET /organization/production_lines/new
  def new
    @organization_production_line = Organization::ProductionLine.new
  end

  # GET /organization/production_lines/1/edit
  def edit
  end

  # POST /organization/production_lines or /organization/production_lines.json
  def create
    @organization_production_line = Organization::ProductionLine.new(organization_production_line_params)

    respond_to do |format|
      if @organization_production_line.save
        format.html { redirect_to @organization_production_line, notice: t('.notice') }
        format.json { render :show, status: :created, location: @organization_production_line }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization_production_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization/production_lines/1 or /organization/production_lines/1.json
  def update
    respond_to do |format|
      if @organization_production_line.update(organization_production_line_params)
        format.html { redirect_to @organization_production_line, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @organization_production_line }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization_production_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization/production_lines/1 or /organization/production_lines/1.json
  def destroy
    @organization_production_line.destroy!

    respond_to do |format|
      format.html { redirect_to organization_production_lines_path, status: :see_other, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  # -- -------------------------------------------------------------------------
  # -- Protected Methods -------------------------------------------------------

  protected

  # -- -------------------------------------------------------------------------
  # -- Private Methods ---------------------------------------------------------

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_organization_production_line
      @organization_production_line = Organization::ProductionLine.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def organization_production_line_params
      params.expect(organization_production_line: %i[code name description organization_producion_line_id status])
    end
end

app/helpers/organization/areas_helper.rb
# frozen_string_literal: true

module Organization::AreasHelper
end

app/helpers/organization/plants_helper.rb
# frozen_string_literal: true

module Organization::PlantsHelper
end

app/helpers/organization/production_lines_helper.rb
# frozen_string_literal: true

module Organization::ProductionLinesHelper
end

app/views/organization/areas/_area.html.erb
<div id="<%= dom_id area %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Code:</strong>
    <%= area.code %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= area.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= area.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Organization plant:</strong>
    <%= area.organization_plant_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= area.status %>
  </p>

</div>

app/views/organization/areas/_area_select.html.erb
<%= turbo_frame_tag 'areas_select' do %>
  <%= select_tag 'maintenance_asset[organization_area_id]',
                 options_from_collection_for_select(areas, :id, :name),
                 {
                   prompt: t('.select_area'),
                   class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg
                           focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5
                           dark:bg-gray-700 dark:border-gray-600 dark:text-white',
                   data: { asset_location_target: 'area',
                           action: 'change->asset-location#updateProductionLines' } } %>
<% end %>

app/views/organization/areas/_form.html.erb
<%= form_with(model: organization_area, class: "contents") do |form| %>
  <% if organization_area.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(organization_area.errors.count, "error") %> prohibited this organization_area from being saved:</h2>

      <ul>
        <% organization_area.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :code %>
    <%= form.text_field :code, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :organization_plant_id %>
    <%= form.text_field :organization_plant_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.number_field :status, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/organization/areas/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing area</h1>

  <%= render "form", organization_area: @organization_area %>

  <%= link_to "Show this area", @organization_area, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to areas", organization_areas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/organization/areas/index.html.erb
<% breadcrumb :organization_areas %>
<% resource_class = Organization::Area %>
<% resource_key = "activerecord.models.#{resource_class.model_name.i18n_key}" %>
<% content_for :title, full_title(t("#{resource_key}.other")) %>
<div class="p-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5 dark:bg-gray-800
            dark:border-gray-700">
  <div class="w-full mb-1">
    <div class="mb-4">
      <%= render partial: 'shared/breadcrumb' %>
      <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">
        <%= t('.all_areas', count: @pagy.count) %>
      </h1>
    </div>
    <%= render partial: 'shared/table/header', locals: { resource_class: resource_class } %>
  </div>
</div>
<div class="flex flex-col">
  <div class="overflow-x-auto">
    <div class="inline-block min-w-full align-middle">
      <div class="overflow-hidden shadow">
        <table class="min-w-full divide-y divide-gray-200 table-fixed dark:divide-gray-600">
          <thead class="bg-gray-100 dark:bg-gray-700 text-xs font-medium text-left text-gray-500 uppercase
                        dark:text-gray-400">
          <tr>
            <th scope="col" class="p-4">
              <%= t("activerecord.attributes.#{resource_class.model_name.i18n_key}.code") %>
            </th>
            <th scope="col" class="p-4">
              <%= t("activerecord.attributes.#{resource_class.model_name.i18n_key}.name") %>
            </th>
            <th scope="col" class="p-4">
              <%= t("activerecord.attributes.#{resource_class.model_name.i18n_key}.status") %>
            </th>
            <th scope="col" class="p-4">
              Acciones
            </th>
          </tr>
          </thead>
          <tbody id="assets" class="bg-white dark:bg-gray-800 dark:divide-gray-700">
          <% @records.each do |area| %>
            <tr class="border-b dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700">
              <td class="p-4 text-gray-500 whitespace-nowrap dark:text-gray-400">
                <%= area.code %>
              </td>
              <td class="p-4 text-gray-500 whitespace-nowrap dark:text-gray-400">
                <%= area.name %>
              </td>
              <td class="p-4 text-gray-500 whitespace-nowrap dark:text-gray-400">
                <div class="flex items-center">
                  <% color = area.status_color %>
                  <div class="h-2.5 w-2.5 rounded-full mr-2 bg-<%= color %>-400"></div>
                  <%= area.t_enum(:status) %>
                </div>
              </td>
              <td class="p-4 space-x-2 whitespace-nowrap">
                <div class="flex align-center justify-left space-x-2">
                  <%= link_to area,
                              class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white
                                      bg-green-600 rounded-lg hover:bg-green-800 focus:ring-4 focus:ring-green-300 
                                      dark:focus:ring-green-900' do %>
                    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                            d="M12 4.5c-5 0-9 3.5-10 7.5 1 4 5 7.5 10 7.5s9-3.5 10-7.5c-1-4-5-7.5-10-7.5zm0 13a5.5 5.5 0
                               1 1 0-11 5.5 5.5 0 0 1 0 11zm0-9a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7z"
                            clip-rule="evenodd"></path>
                    </svg>
                  <% end %>
                  <%= link_to edit_organization_area_path(area),
                              class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white
                                      bg-yellow-600 rounded-lg hover:bg-yellow-800 focus:ring-4 focus:ring-yellow-300 
                                      dark:focus:ring-yellow-900' do %>
                    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path>
                      <path fill-rule="evenodd"
                            d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"
                            clip-rule="evenodd"></path>
                    </svg>
                  <% end %>
                  <%= confirmation_modal_button(area,
                                                class: 'inline-flex items-center px-3 py-2 text-sm font-medium
                                                        text-center text-white bg-red-600 rounded-lg hover:bg-red-800
                                                        focus:ring-4 focus:ring-red-300 dark:focus:ring-red-900') do %>
                    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                            d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0
                               100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1
                               1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                            clip-rule="evenodd"></path>
                    </svg>
                  <% end %>

                  <%= render_confirmation_modal(area,
                                                path: maintenance_asset_path(area),
                                                message: t('shared.modals.delete_message',
                                                           resource: t("#{resource_key}.one").downcase),
                                                confirm_button_text: t('shared.modals.delete_button'),
                                                cancel_button_text: t('shared.modals.cancel_button')) %>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'shared/pagination', locals: { pagy: @pagy } %>

app/views/organization/areas/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New area</h1>

  <%= render "form", organization_area: @organization_area %>

  <%= link_to "Back to areas", organization_areas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/organization/areas/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @organization_area %>

    <%= link_to "Edit this area", edit_organization_area_path(@organization_area), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to areas", organization_areas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this area", @organization_area, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>