config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the unauthenticated root path route ("/")
  unauthenticated do
    root 'public#home'
  end

  # Defines the authenticated root path route ("/") for the User model
  authenticated :user do
    root 'dashboard#show', as: :authenticated_root
  end

  # Public routes
  get 'help', to: 'public#help'
  get 'about', to: 'public#about'
  get 'contact', to: 'public#contact'

  # Defines the routes for the Devise User model
  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations',
                            passwords: 'users/passwords',
                            unlocks: 'users/unlocks',
                            confirmations: 'users/confirmations' },
             path: '',
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'signup',
                           edit: 'profile' }

  namespace :common do
    resources :measure_units
    resources :measure_unit_types
    resources :languages
    resources :timezones
    resources :currencies
    resources :countries
  end

  namespace :organization do
    resources :plants do
      member do
        get :areas
      end
    end

    resources :areas do
      member do
        get :production_lines
      end
    end

    resources :production_lines
  end

  namespace :maintenance do
    resources :plans do
      collection do
        get :new_resource_fields
      end
    end
    resources :technicians
    resources :manufacturers
    resources :asset_types

    resources :assets do
      resources :asset_documents, path: 'documents', shallow: true
      resources :asset_assignees, path: 'assignees', shallow: true,
                only: %i[ index create destroy ]

      member do
        get :components, defaults: { format: :turbo_stream }
      end
    end
  end

  namespace :settings do
    root 'general#index'
  end
end

app/models/maintenance.rb
# frozen_string_literal: true

module Maintenance
  def self.table_name_prefix
    'maintenance_'
  end
end

app/models/maintenance/asset_assignee.rb
# frozen_string_literal: true

class Maintenance::AssetAssignee < ApplicationRecord
  # -- -------------------------------------------------------------------------
  # -- Constants ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Concerns ----------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Attributes --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Extensions --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Enums -------------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Associations ------------------------------------------------------------
  belongs_to :asset, class_name: 'Maintenance::Asset',
             foreign_key: :maintenance_asset_id
  belongs_to :technician, class_name: 'Maintenance::Technician',
             foreign_key: :maintenance_technician_id

  # -- -------------------------------------------------------------------------
  # -- Validations -------------------------------------------------------------
  validates :maintenance_asset_id,
            uniqueness: { scope: %i[maintenance_technician_id] }

  # -- -------------------------------------------------------------------------
  # -- Callbacks ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Scopes ------------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Delegations -------------------------------------------------------------
  delegate :full_name, to: :technician
  delegate :email, to: :technician
  delegate :profile, to: :technician
  delegate :avatar, to: :technician
  delegate :specialty, to: :technician
  delegate :certification_level, to: :technician

  # -- -------------------------------------------------------------------------
  # -- Class Methods -----------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Instance Methods --------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Private Methods ---------------------------------------------------------
end

app/controllers/maintenance/asset_assignees_controller.rb
# frozen_string_literal: true

class Maintenance::AssetAssigneesController < ApplicationController
  # -- -------------------------------------------------------------------------
  # -- Constants ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Concerns ----------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Extensions --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Callbacks ------------------------------------------------
  before_action :set_maintenance_asset_assignee, only: %i[ show edit update destroy ]

  # -- -------------------------------------------------------------------------
  # -- Helper methods ----------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Actions -----------------------------------------------------------------

  # GET /maintenance/asset_assignees or /maintenance/asset_assignees.json
  def index
    @maintenance_asset_assignees = Maintenance::AssetAssignee.all
  end

  # GET /maintenance/asset_assignees/1 or /maintenance/asset_assignees/1.json
  def show
  end

  # GET /maintenance/asset_assignees/new
  def new
    @maintenance_asset_assignee = Maintenance::AssetAssignee.new
  end

  # GET /maintenance/asset_assignees/1/edit
  def edit
  end

  # POST /maintenance/asset_assignees or /maintenance/asset_assignees.json
  def create
    @maintenance_asset_assignee = Maintenance::AssetAssignee.new(maintenance_asset_assignee_params)

    respond_to do |format|
      if @maintenance_asset_assignee.save
        format.html { redirect_to @maintenance_asset_assignee, notice: t('.notice') }
        format.json { render :show, status: :created, location: @maintenance_asset_assignee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance_asset_assignee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance/asset_assignees/1 or /maintenance/asset_assignees/1.json
  def update
    respond_to do |format|
      if @maintenance_asset_assignee.update(maintenance_asset_assignee_params)
        format.html { redirect_to @maintenance_asset_assignee, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @maintenance_asset_assignee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance_asset_assignee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance/asset_assignees/1 or /maintenance/asset_assignees/1.json
  def destroy
    @maintenance_asset_assignee.destroy!

    respond_to do |format|
      format.html { redirect_to maintenance_asset_assignees_path, status: :see_other, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  # -- -------------------------------------------------------------------------
  # -- Protected Methods -------------------------------------------------------

  protected

  # -- -------------------------------------------------------------------------
  # -- Private Methods ---------------------------------------------------------

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_asset_assignee
      @maintenance_asset_assignee = Maintenance::AssetAssignee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_asset_assignee_params
      params.expect(maintenance_asset_assignee: %i[ maintenance_asset_id maintenance_technician_id ])
    end
end

app/controllers/maintenance/asset_components_controller.rb
# frozen_string_literal: true

class Maintenance::AssetComponentsController < ApplicationController
  # -- -------------------------------------------------------------------------
  # -- Constants ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Concerns ----------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Extensions --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Callbacks ------------------------------------------------
  before_action :set_maintenance_asset_component, only: %i[ show edit update destroy ]

  # -- -------------------------------------------------------------------------
  # -- Helper methods ----------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Actions -----------------------------------------------------------------

  # GET /maintenance/asset_components or /maintenance/asset_components.json
  def index
    @maintenance_asset_components = Maintenance::AssetComponent.all
  end

  # GET /maintenance/asset_components/1 or /maintenance/asset_components/1.json
  def show
  end

  # GET /maintenance/asset_components/new
  def new
    @maintenance_asset_component = Maintenance::AssetComponent.new
  end

  # GET /maintenance/asset_components/1/edit
  def edit
  end

  # POST /maintenance/asset_components or /maintenance/asset_components.json
  def create
    @maintenance_asset_component = Maintenance::AssetComponent.new(maintenance_asset_component_params)

    respond_to do |format|
      if @maintenance_asset_component.save
        format.html { redirect_to @maintenance_asset_component, notice: t('.notice') }
        format.json { render :show, status: :created, location: @maintenance_asset_component }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance_asset_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance/asset_components/1 or /maintenance/asset_components/1.json
  def update
    respond_to do |format|
      if @maintenance_asset_component.update(maintenance_asset_component_params)
        format.html { redirect_to @maintenance_asset_component, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @maintenance_asset_component }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance_asset_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance/asset_components/1 or /maintenance/asset_components/1.json
  def destroy
    @maintenance_asset_component.destroy!

    respond_to do |format|
      format.html { redirect_to maintenance_asset_components_path, status: :see_other, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  # -- -------------------------------------------------------------------------
  # -- Protected Methods -------------------------------------------------------

  protected

  # -- -------------------------------------------------------------------------
  # -- Private Methods ---------------------------------------------------------

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_asset_component
      @maintenance_asset_component = Maintenance::AssetComponent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_asset_component_params
      params.expect(maintenance_asset_component: %i[ :maintenance_asset_id, :name, :description, :quantity, :specifications, :replacement_period, :active ])
    end
end

app/controllers/maintenance/asset_documents_controller.rb
# frozen_string_literal: true

class Maintenance::AssetDocumentsController < ApplicationController
  # -- -------------------------------------------------------------------------
  # -- Constants ---------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Concerns ----------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Extensions --------------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Callbacks ---------------------------------------------------------------
  before_action :set_maintenance_asset_document, only: %i[ show edit update destroy ]

  # -- -------------------------------------------------------------------------
  # -- Helper methods ----------------------------------------------------------

  # -- -------------------------------------------------------------------------
  # -- Actions -----------------------------------------------------------------

  # GET /maintenance/asset_documents or /maintenance/asset_documents.json
  def index
    @maintenance_asset_documents = Maintenance::AssetDocument.all
  end

  # GET /maintenance/asset_documents/1 or /maintenance/asset_documents/1.json
  def show
  end

  # GET /maintenance/asset_documents/new
  def new
    @maintenance_asset_document = Maintenance::AssetDocument.new
  end

  # GET /maintenance/asset_documents/1/edit
  def edit
  end

  # POST /maintenance/asset_documents or /maintenance/asset_documents.json
  def create
    @maintenance_asset_document = Maintenance::AssetDocument.new(maintenance_asset_document_params)

    respond_to do |format|
      if @maintenance_asset_document.save
        format.html { redirect_to @maintenance_asset_document, notice: t('.notice') }
        format.json { render :show, status: :created, location: @maintenance_asset_document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance_asset_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance/asset_documents/1 or /maintenance/asset_documents/1.json
  def update
    respond_to do |format|
      if @maintenance_asset_document.update(maintenance_asset_document_params)
        format.html { redirect_to @maintenance_asset_document, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @maintenance_asset_document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance_asset_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance/asset_documents/1 or /maintenance/asset_documents/1.json
  def destroy
    @maintenance_asset_document.destroy!

    respond_to do |format|
      format.html { redirect_to maintenance_asset_documents_path, status: :see_other, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  # -- -------------------------------------------------------------------------
  # -- Protected Methods -------------------------------------------------------

  protected

  # -- -------------------------------------------------------------------------
  # -- Private Methods ---------------------------------------------------------

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_asset_document
      @maintenance_asset_document = Maintenance::AssetDocument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_asset_document_params
      params.expect(maintenance_asset_document: %i[ :maintenance_asset_id, :document_type, :name, :description, :version, :expiration_date, :active ])
    end
end

app/views/maintenance/asset_types/_asset_type.html.erb
<div id="<%= dom_id asset_type %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">
      <%= t('activerecord.attributes.maintenance/asset_type.code') %>:
    </strong>
    <%= asset_type.code %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">
      <%= t('activerecord.attributes.maintenance/asset_type.name') %>:
    </strong>
    <%= asset_type.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">
      <%= t('activerecord.attributes.maintenance/asset_type.description') %>:
    </strong>
    <%= asset_type.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">
      <%= t('activerecord.attributes.maintenance/asset_type.status') %>:
    </strong>
    <%= asset_type.t_enum(:status) %>
  </p>

</div>

app/views/maintenance/asset_types/edit.html.erb
<% breadcrumb :edit_maintenance_asset_type, @maintenance_asset_type %>
<div class="p-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5 dark:bg-gray-800
            dark:border-gray-700">
  <div class="w-full mb-1">
    <%= render 'shared/breadcrumb' %>
    <div class="flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:items-center sm:justify-between">
      <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">
        <%= "#{@maintenance_asset_type.code} - #{@maintenance_asset_type.name}" %>
      </h1>
      <div class="flex items-center space-x-2 justify-end">
        <%= link_to t('shared.forms.cancel_button'), maintenance_asset_type_path(@maintenance_asset_type),
                    class: 'inline-flex items-center justify-center px-4 py-2 ml-2 text-sm font-medium text-center
                            text-white rounded-lg bg-gray-400 hover:bg-gray-500 focus:ring-4 focus:ring-gray-300
                            dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800' %>
        <%= button_tag type: 'submit', form: 'asset_type_form',
                       class: 'inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-center
                               text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300
                               dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' do %>
          <svg class="w-4 h-4 mr-2 -ml-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
               width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M5 11.917 9.724 16.5 19 7.5"/>
          </svg>
          <%= t('shared.forms.save_button') %>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col">
      <%= render 'form', maintenance_asset_type: @maintenance_asset_type %>
    </div>
  </div>
</div>

app/views/maintenance/asset_types/index.html.erb
<% breadcrumb :maintenance_asset_types %>
<% resource_class = Maintenance::AssetType %>
<% resource_key = "activerecord.models.#{resource_class.model_name.i18n_key}" %>
<% content_for :title, full_title(t("#{resource_key}.other")) %>
<div class="p-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5 dark:bg-gray-800
            dark:border-gray-700">
  <div class="w-full mb-1">
    <div class="mb-4">
      <%= render partial: 'shared/breadcrumb' %>
      <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">
        <%= t('.all_asset_types', count: @pagy.count) %>
      </h1>
    </div>
    <%= render partial: 'shared/table/header', locals: { resource_class: resource_class } %>
  </div>
</div>
<div class="flex flex-col">
  <div class="overflow-x-auto">
    <div class="inline-block min-w-full align-middle">
      <div class="overflow-hidden shadow">
        <table class="min-w-full divide-y divide-gray-200 table-fixed dark:divide-gray-600">
          <thead class="bg-gray-100 dark:bg-gray-700 text-xs font-medium text-left text-gray-500 uppercase
                        dark:text-gray-400">
          <tr>
            <th scope="col" class="p-4">
              <%= t("activerecord.attributes.#{resource_class.model_name.i18n_key}.code") %>
            </th>
            <th scope="col" class="p-4">
              <%= t("activerecord.attributes.#{resource_class.model_name.i18n_key}.name") %>
            </th>
            <th scope="col" class="p-4">
              <%= t("activerecord.attributes.#{resource_class.model_name.i18n_key}.status") %>
            </th>
            <th scope="col" class="p-4">
              Acciones
            </th>
          </tr>
          </thead>
          <tbody id="assets" class="bg-white dark:bg-gray-800 dark:divide-gray-700">
          <% @records.each do |maintenance_asset_type| %>
            <tr class="border-b dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700">
              <td class="p-4 text-gray-500 whitespace-nowrap dark:text-gray-400">
                <%= maintenance_asset_type.code %>
              </td>
              <td class="p-4 text-gray-500 whitespace-nowrap dark:text-gray-400">
                <%= maintenance_asset_type.name %>
              </td>
              <td class="p-4 text-gray-500 whitespace-nowrap dark:text-gray-400">
                <div class="flex items-center">
                  <% color = maintenance_asset_type.status_color %>
                  <div class="h-2.5 w-2.5 rounded-full mr-2 bg-<%= color %>-400"></div>
                  <%= maintenance_asset_type.t_enum(:status) %>
                </div>
              </td>
              <td class="p-4 space-x-2 whitespace-nowrap">
                <div class="flex align-center justify-left space-x-2">
                  <%= link_to maintenance_asset_type,
                              class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white
                                      bg-green-600 rounded-lg hover:bg-green-800 focus:ring-4 focus:ring-green-300 
                                      dark:focus:ring-green-900' do %>
                    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                            d="M12 4.5c-5 0-9 3.5-10 7.5 1 4 5 7.5 10 7.5s9-3.5 10-7.5c-1-4-5-7.5-10-7.5zm0 13a5.5 5.5 0
                               1 1 0-11 5.5 5.5 0 0 1 0 11zm0-9a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7z"
                            clip-rule="evenodd"></path>
                    </svg>
                  <% end %>
                  <%= link_to edit_maintenance_asset_type_path(maintenance_asset_type),
                              class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white
                                      bg-yellow-600 rounded-lg hover:bg-yellow-800 focus:ring-4 focus:ring-yellow-300 
                                      dark:focus:ring-yellow-900' do %>
                    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path>
                      <path fill-rule="evenodd"
                            d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"
                            clip-rule="evenodd"></path>
                    </svg>
                  <% end %>
                  <%= confirmation_modal_button(maintenance_asset_type,
                                                class: 'inline-flex items-center px-3 py-2 text-sm font-medium
                                                        text-center text-white bg-red-600 rounded-lg hover:bg-red-800
                                                        focus:ring-4 focus:ring-red-300 dark:focus:ring-red-900') do %>
                    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                            d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0
                               100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1
                               1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                            clip-rule="evenodd"></path>
                    </svg>
                  <% end %>

                  <%= render_confirmation_modal(maintenance_asset_type,
                                                path: maintenance_asset_path(maintenance_asset_type),
                                                message: t('.delete_message'),
                                                confirm_button_text: t('.delete'),
                                                cancel_button_text: t('.cancel')) %>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'shared/pagination', locals: { pagy: @pagy } %>

app/views/maintenance/asset_types/new.html.erb
<% breadcrumb :new_maintenance_asset_type %>
<div class="p-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5 dark:bg-gray-800
            dark:border-gray-700">
  <div class="w-full mb-1">
    <%= render 'shared/breadcrumb' %>
    <div class="flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:items-center sm:justify-between">
      <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">
        <%= t('.title') %>
      </h1>
      <div class="flex items-center space-x-2 justify-end">
        <%= link_to t('shared.forms.cancel_button'), maintenance_asset_types_path,
                    class: 'inline-flex items-center justify-center px-4 py-2 ml-2 text-sm font-medium text-center
                            text-white rounded-lg bg-gray-400 hover:bg-gray-500 focus:ring-4 focus:ring-gray-300
                            dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800' %>
        <%= button_tag type: 'submit', form: 'asset_type_form',
                       class: 'inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-center
                               text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300
                               dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' do %>
          <svg class="w-4 h-4 mr-2 -ml-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
               width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M5 11.917 9.724 16.5 19 7.5"/>
          </svg>
          <%= t('shared.forms.save_button') %>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col">
      <%= render 'form', maintenance_asset_type: @maintenance_asset_type %>
    </div>
  </div>
</div>

app/views/maintenance/asset_types/show.html.erb
<% breadcrumb :maintenance_asset_type, @maintenance_asset_type %>
<div class="p-4 bg-white block sm:flex items-center justify-between border-b border-gray-200 lg:mt-1.5 dark:bg-gray-800
            dark:border-gray-700">
  <div class="w-full mb-1">
    <%= render 'shared/breadcrumb' %>
    <div class="flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:items-center sm:justify-between">
      <div class="flex flex-col sm:flex-row sm:items-center gap-2">
        <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">
          <%= "#{@maintenance_asset_type.code}: #{@maintenance_asset_type.name}" %>
        </h1>
        <% color = @maintenance_asset_type.status_color %>
        <span class="inline-flex items-center bg-<%= color %>-100 text-<%= color %>-800 text-sm font-medium px-3 py-1
                       rounded-full dark:bg-<%= color %>-900 dark:text-<%= color %>-300">
            <%= @maintenance_asset_type.t_enum(:status) %>
          </span>
      </div>
      <div class="flex items-center space-x-2 justify-end">
        <%= link_to t('shared.forms.cancel_button'), maintenance_asset_types_path,
                    class: 'inline-flex items-center justify-center px-4 py-2 ml-2 text-sm font-medium text-center
                            text-white rounded-lg bg-gray-400 hover:bg-gray-500 focus:ring-4 focus:ring-gray-300
                            dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800' %>
        <%= link_to edit_maintenance_asset_type_path(@maintenance_asset_type),
                    class: 'inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white
                              rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600
                              dark:hover:bg-blue-700 dark:focus:ring-blue-800' do %>
          <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path>
            <path fill-rule="evenodd"
                  d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z"
                  clip-rule="evenodd"></path>
          </svg>
          <%= t('shared.forms.edit_button') %>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col">
      <%= render @maintenance_asset_type %>
    </div>
  </div>
</div>